spring:
  application:
    name: client-caller

#服务端口
server:
  port: 10213

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

app:
  service-url: http://CLIENT-PROVIDER/